icp_localiser_node:
  ros__parameters:
    point_cloud_topic: "/velodyne_points" # "/carla/ego_vehicle/lidar"  point cloud ros topic to subscribe to
    imu_topic: "/sd_current_IMU" #imu ros topic to subscribe to
    pose_topic: "/my_icp_pose" #pose ros topic to which to publish

    # Downsample Filter
    leaf_size: 1.0 #leaf size for voxel grid

    # Ground Filtering
    dist_threshold: 2.5 #distance threshold for RASNSAC to consider a point as inlier
    eps_angle: 20.0 #allowed difference of angles in degrees for perpendicular plane model

    # Box Filtering
    minX: 0.0 #min point of box filter
    minY: 0.0
    minZ: -3.0
    maxX: 50.0 #max point of box filter
    maxY: 25.0
    maxZ: 3.0

    # Noise Filtering
    mean_k: 50.0 #number of neighbors to analyze for each point for noise removal
    std_mul: 1.5 #standard deviation multiplication threshold for noise removal



    # ICP Parameters
    transformation_epsilon: 2.5
    euclidean_fitness_epsilon: 0.8 #maximum allowed Euclidean error between two consecutive steps in the ICP loop
    max_correspondence_distance: 20.5 #correspondences with higher distances will be ignored
    max_iters: 65.0 #max number of registration iterations

    # transformation_epsilon: 20.0 #minimum transformation difference for termination condition
    # euclidean_fitness_epsilon: 0.8 #maximum allowed Euclidean error between two consecutive steps in the ICP loop
    # max_correspondence_distance: 30.5 #correspondences with higher distances will be ignored
    # max_iters: 50.0 #max number of registration iterations

    fit_score: 17000 #170
    recov_fit_score: 17000 #170

    resolution_points_init: 0.1
    resolution_points_recov: 4.0


    init_x:  -27.8
    init_y: -3.4
    init_z: 2.4

    map_path: "/home/mcav/mcav_ws/src/mcav_autonomy/project_map/icp_localiser/n1level4-autoware-221006.pcd"
    #map_path: "/home/mcav/liam_ws/localisation/pointclouds/10kmhsquare_Voxel.pcd"
    use_sim_time: false
